export const metadata = { title: 'Privacy — One Dollar Quote' };

export default function PrivacyPage() {
  return (
    <div className="legal">
      <h1>Privacy Policy</h1>
      <p className="updated">Last updated: 2026</p>

      <p>
        This policy explains what personal data One Dollar Quote processes and why, in line with the
        EU General Data Protection Regulation (GDPR).
      </p>

      <h2>1. Who is responsible</h2>
      <p>
        The data controller is Arber Kadriu. For any privacy request, contact{' '}
        <a href="mailto:myonedollarquote@gmail.com">myonedollarquote@gmail.com</a>.
      </p>

      <h2>2. What data is processed</h2>
      <ul>
        <li>
          <strong>Content you publish</strong>: the text, signature and optional link on your page.
          This content is public by design.
        </li>
        <li>
          <strong>Payment data</strong>: handled directly by Stripe. Card details are never stored
          on this Site.
        </li>
        <li>
          <strong>Technical data</strong>: standard server logs (such as IP address and request
          data) generated by the hosting and database providers for security and operation.
        </li>
        <li>
          <strong>Admin session</strong>: an essential, secure cookie used only for the site
          administrator to log in. No advertising or tracking cookies are used.
        </li>
      </ul>

      <h2>3. Why, and on what legal basis</h2>
      <ul>
        <li>To provide the service and publish your page — performance of a contract;</li>
        <li>To process your payment — performance of a contract and legal obligation;</li>
        <li>To moderate content and keep the Site secure — legitimate interest;</li>
        <li>To use published pages for content and promotion — as agreed in the Terms.</li>
      </ul>

      <h2>4. Who processes the data</h2>
      <p>
        The Site relies on trusted providers acting as processors: <strong>Stripe</strong>
        {' '}(payments), <strong>Supabase</strong> (database) and <strong>Vercel</strong> (hosting).
        Some of these providers may process data outside the European Union, under appropriate legal
        safeguards.
      </p>

      <h2>5. How long data is kept</h2>
      <p>
        Published content is permanent and remains part of the book unless it is removed. Payment
        records are kept for as long as required by law. Technical logs are kept for a limited period
        by the providers.
      </p>

      <h2>6. Your rights</h2>
      <p>
        You have the right to access, correct, delete, object to, or port your personal data. To
        exercise these rights, email{' '}
        <a href="mailto:myonedollarquote@gmail.com">myonedollarquote@gmail.com</a>. Please note that
        because published pages are public and permanent by nature, the deletion of published
        content may be limited; refund requests follow the Terms (15 days).
      </p>

      <h2>7. Cookies</h2>
      <p>
        The Site does not use advertising or analytics cookies. The only cookie is an essential,
        secure session cookie for the administrator.
      </p>

      <h2>8. Contact</h2>
      <p>
        For any question about your data, contact{' '}
        <a href="mailto:myonedollarquote@gmail.com">myonedollarquote@gmail.com</a>.
      </p>

      <a className="back" href="/">← Back to the book</a>
    </div>
  );
}
